### ISSUE TITLE
Various Backend Issues

### ISSUE THREAD

**Issue by alex-stetson** [TournamentBuzz/main#79] opened 2019-04-08 20:46 UTC
## Story/Task Details
- Team deletion is broken
- Manual match creation is still broken
- Match deletion may be broken (can't be tested because match creation is broken)

**Comment by dli357** [comment] 2019-04-10 06:35
Working on a fix!

**Comment by dli357** [comment] 2019-04-10 07:39
Resolved via 969d0473f53682072cc215c1562fcc8b3b91ffea.

- Team deletion was a frontend issue
- I was unable to reproduce the match creation issue.
- I was able to confirm that match deletion is functional.

**Closed** 2020-04-26 05:49 UTC
